plugins {
    id 'org.jetbrains.kotlin.jvm'
}
dependencies {
    annotationProcessor "org.mapstruct:mapstruct-processor:$mapStructVersion"

    implementation(project(":Parser"))

    implementation "org.mapstruct:mapstruct:$mapStructVersion"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa:$springVersion"
    implementation "org.springframework.boot:spring-boot-starter-web:$springVersion"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

bootJar {
    enabled = true
}

jar {
    enabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
