version: "3.8"
services:
    postgres:
        image: postgres:16.4
        container_name: postgresql_gastrofest
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/1.init.sql
            - ./db/dump.sql:/docker-entrypoint-initdb.d/2.dump.sql
